name: CI

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-example-on-device:
    runs-on: self-hosted
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run on-device examples
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          source ${ASCEND_HOME_PATH}/bin/setenv.bash && ./ci.sh -p a2a3 -d 9 --parallel -c 6622890 -t 600 --clone-protocol https
